#!/usr/bin/env python

import dataclasses
import functools

import geometry_msgs.msg
import mlflow
import rospy

import test_msgs.srv

def message_interface(request, model):
  """Converts the inputs and outputs to and from ROS messages respectively"""

  # Build a model request
  # experience_cloud_headers = [c.header for c in request.experience_clouds]
  # experience_clouds = [ros_numpy.point_cloud2.pointcloud2_to_xyz_array(c) for c in request.experience_clouds]
  # query_clouds = [ros_numpy.point_cloud2.pointcloud2_to_xyz_array(request.query_cloud)]
  # request = Request(experience_clouds, query_clouds)

  # Use the model to make the prediction
  predictions = model.predict(request)

  # Build a service response from the prediction
  response = test_msgs.srv.PredictIrisResponse()
  
  reponse.predicted_class.append(predictions)

  return response


def main():
  """Start the egonn node with the message interface function as the service command"""
  rospy.init_node("logreg", anonymous=False)

  # Pull in the egonn model
  pyfunc_model = mlflow.pyfunc.load_model(model_uri=f"/model")
  rospy.loginfo("Model loaded")

  rospy.Service(
      "~compute_iris",
      test_msgs.srv.PredictIris,
      functools.partial(message_interface, model=pyfunc_model),
  )

  rospy.spin()


if __name__ == "__main__":
  main()
