### To be appended to the mlflow generated dockerfile ###

# Disable any interactive prompts
ARG DEBIAN_FRONTEND=noninteractive

# Create script that activates the mlflow conda env or virtual env, depending on what got installed
RUN echo 'if [ -e /miniconda/bin/activate ]; then' >> /activate_mlflow_env.bash \
  && echo '  source /miniconda/bin/activate custom_env' >> /activate_mlflow_env.bash \
  && echo 'fi' >>/activate_mlflow_env.bash \
  && echo 'if [ -e /opt/activate ]; then' >> /activate_mlflow_env.bash \
  && echo '  source /opt/activate' >> /activate_mlflow_env.bash \
  && echo 'fi' >>/activate_mlflow_env.bash 

# Create script that sources the ROS environment
RUN echo 'source /opt/ros/noetic/setup.bash' >> /activate_ros_env.bash \
  && echo 'if [ -e /workspace/install/setup.bash ]; then' >> /activate_ros_env.bash \
  && echo '  source /workspace/install/setup.bash' >> /activate_ros_env.bash \
  && echo 'fi' >> /activate_ros_env.bash

# Install rospkg into mlflow virtualenv or conda environment
RUN echo 'source /activate_mlflow_env.bash' >> /install_rospkg.bash \ 
  && echo 'pip install rospkg' >>/install_rospkg.bash \
  && /bin/bash /install_rospkg.bash \
  && rm /install_rospkg.bash

WORKDIR /workspace

FROM base as dev
# Add ROS source commands to .bashrc for convenience 
RUN echo 'source /activate_ros_env.bash' >> /root/.bashrc \
    && echo 'source /activate_mlflow_env.bash' >> /root/.bashrc 
RUN apt-get update && apt-get install --assume-yes --no-install-recommends python3-colcon-common-extensions 

# Build the model's ROS node and install it on the image 
FROM base as build
RUN apt-get update && apt-get install --assume-yes --no-install-recommends python3-colcon-common-extensions 
COPY {{ rospkg_dir }} src

# Build ROS packages 
RUN . /opt/ros/{{ ros_distro }}/setup.sh && \
    colcon build --event-handlers console_cohesion+ status- --cmake-args -DPYTHON_EXECUTABLE=/usr/bin/python3 

FROM base as prod
COPY --from=build /workspace/install install

# create entrypoint script that runs the ROS node
RUN echo 'source /activate_ros_env.bash' >> /entrypoint.bash \
  && echo 'source /activate_mlflow_env.bash' >> /entrypoint.bash \
  # launch ROS node
  && echo "rosrun {{ model_name }} serve_model.py" >> /entrypoint.bash

ENTRYPOINT ["/bin/bash", "/entrypoint.bash"]
